In [ ]:
#!/usr/bin/python
# -*- coding: utf-8 -*-

__author__      = "Matheus Dib, Fabio de Miranda"


import cv2
import numpy as np
from matplotlib import pyplot as plt
import time

# If you want to open a video, just change this path
#cap = cv2.VideoCapture('hall_box_battery.mp4')

# Parameters to use when opening the webcam.
cap = cv2.VideoCapture(0)
cap.set(cv2.CAP_PROP_FRAME_WIDTH, 640)
cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 480)

lower = 0
upper = 1

# Returns an image containing the borders of the image
# sigma is how far from the median we are setting the thresholds
def auto_canny(image, sigma=0.33):
    # compute the median of the single channel pixel intensities
    v = np.median(image)

    # apply automatic Canny edge detection using the computed median
    lower = int(max(0, (1.0 - sigma) * v))
    upper = int(min(255, (1.0 + sigma) * v))
    edged = cv2.Canny(image, lower, upper)

    # return the edged image
    return edged



while(True):
    # Capture frame-by-frame
    print("New frame")
    ret, frame = cap.read()

    # Convert the frame to grayscale
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    # A gaussian blur to get rid of the noise in the image
    blur = cv2.GaussianBlur(gray,(5,5),0)
    #blur = gray
    # Detect the edges present in the image
    bordas = auto_canny(blur)


    circles = []


    # Obtains a version of the edges image where we can draw in color
    bordas_color = cv2.cvtColor(bordas, cv2.COLOR_GRAY2BGR)

    # HoughCircles - detects circles using the Hough Method. For an explanation of
    # param1 and param2 please see an explanation here http://www.pyimagesearch.com/2014/07/21/detecting-circles-images-using-opencv-hough-circles/
    circles = None
    circles=cv2.HoughCircles(bordas,cv2.HOUGH_GRADIENT,2,40,param1=50,param2=100,minRadius=5,maxRadius=60)

    if circles is not None:
        circles = np.uint16(np.around(circles))

        for i in circles[0,:]:
            print(i)
            # draw the outer circle
            # cv2.circle(img, center, radius, color[, thickness[, lineType[, shift]]])
            cv2.circle(bordas_color,(i[0],i[1]),i[2],(0,255,0),2)
            # draw the center of the circle
            cv2.circle(bordas_color,(i[0],i[1]),2,(0,0,255),3)

    # Draw a diagonal blue line with thickness of 5 px
    # cv2.line(img, pt1, pt2, color[, thickness[, lineType[, shift]]])
    cv2.line(bordas_color,(0,0),(511,511),(255,0,0),5)

    # cv2.rectangle(img, pt1, pt2, color[, thickness[, lineType[, shift]]])
    cv2.rectangle(bordas_color,(384,0),(510,128),(0,255,0),3)

    # cv2.putText(img, text, org, fontFace, fontScale, color[, thickness[, lineType[, bottomLeftOrigin]]])
    font = cv2.FONT_HERSHEY_SIMPLEX
    cv2.putText(bordas_color,'Ninjutsu ;)',(0,50), font, 2,(255,255,255),2,cv2.LINE_AA)

    #More drawing functions @ http://docs.opencv.org/2.4/modules/core/doc/drawing_functions.html

    # Display the resulting frame
    cv2.imshow('Detector de circulos',bordas_color)
    print("No circles were found")
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
# When everything done, release the capture
cap.release()
cv2.destroyAllWindows()

New frame
[0 0 0]
No circles were found
New frame
[571 117  57]
No circles were found
New frame
[559 107  46]
No circles were found
New frame
[0 0 0]
No circles were found
New frame
[561 103  41]
[211 117  43]
No circles were found
New frame
[551 101  41]
No circles were found
New frame
[567 113  54]
No circles were found
New frame
[561 109  50]
No circles were found
New frame
[541 101  35]
No circles were found
New frame
[563 111  52]
No circles were found
New frame
[549 103  39]
No circles were found
New frame
[547  99  41]
No circles were found
New frame
[0 0 0]
No circles were found
New frame
[177 107  50]
No circles were found
New frame
[589 105  41]
[185 111  41]
No circles were found
New frame
[213 109  50]
[593 101  41]
No circles were found
New frame
[565 115  57]
No circles were found
New frame
[541 103  35]
No circles were found
New frame
[0 0 0]
No circles were found
New frame
[217 117  46]
No circles were found
New frame
[0 0 0]
No circles were found
New frame
[0 0 0]
No c

[487 371  59]
No circles were found
New frame
[493 365  54]
[ 95 359  57]
No circles were found
New frame
[493 365  54]
[ 95 359  57]
No circles were found
New frame
[493 361  54]
[ 93 353  57]
No circles were found
New frame
[493 355  54]
No circles were found
New frame
[491 351  54]
[ 93 343  59]
No circles were found
New frame
[491 343  53]
[ 95 339  54]
No circles were found
New frame
[491 337  54]
[ 99 333  54]
No circles were found
New frame
[491 335  52]
[ 97 329  54]
No circles were found
New frame
[487 331  54]
[ 93 325  57]
No circles were found
New frame
[489 329  53]
[ 95 325  54]
No circles were found
New frame
[487 325  53]
[ 95 321  54]
No circles were found
New frame
[ 93 321  54]
[487 321  54]
No circles were found
New frame
[487 323  52]
[ 95 319  56]
No circles were found
New frame
[487 323  52]
[ 95 319  56]
No circles were found
New frame
[487 321  54]
[ 93 319  54]
No circles were found
New frame
[487 321  54]
No circles were found
New frame
[ 93 315  57]
[489 323

New frame
[517 367  57]
No circles were found
New frame
[517 367  59]
No circles were found
New frame
[517 363  57]
No circles were found
New frame
[515 363  57]
No circles were found
New frame
[517 363  57]
No circles were found
New frame
[517 363  59]
No circles were found
New frame
[519 359  57]
No circles were found
New frame
[517 359  59]
No circles were found
New frame
[519 359  57]
No circles were found
New frame
[519 357  57]
No circles were found
New frame
[521 355  57]
No circles were found
New frame
[519 353  57]
No circles were found
New frame
[517 349  57]
No circles were found
New frame
[517 349  57]
No circles were found
New frame
[517 347  57]
No circles were found
New frame
[515 345  57]
No circles were found
New frame
[515 341  57]
No circles were found
New frame
[517 339  57]
No circles were found
New frame
[515 337  59]
No circles were found
New frame
[515 335  59]
No circles were found
New frame
[515 333  59]
No circles were found
New frame
[ 99 329  59]
[519 329  

[107 241  59]
No circles were found
New frame
[109 243  59]
No circles were found
New frame
[109 245  59]
No circles were found
New frame
[107 245  59]
No circles were found
New frame
[107 245  59]
No circles were found
New frame
No circles were found
New frame
No circles were found
New frame
No circles were found
New frame
No circles were found
New frame
No circles were found
New frame
No circles were found
New frame
No circles were found
New frame
No circles were found
New frame
No circles were found
New frame
No circles were found
New frame
No circles were found
New frame
No circles were found
New frame
No circles were found
New frame
No circles were found
New frame
No circles were found
New frame
No circles were found
New frame
No circles were found
New frame
No circles were found
New frame
No circles were found
New frame
No circles were found
New frame
No circles were found
New frame
No circles were found
New frame
No circles were found
New frame
No circles were found
New frame
No

New frame
[159 297  59]
[567 317  55]
No circles were found
New frame
[163 297  59]
[569 317  54]
No circles were found
New frame
[573 315  56]
No circles were found
New frame
[583 313  57]
No circles were found
New frame
[575 315  56]
No circles were found
New frame
[575 315  57]
No circles were found
New frame
[585 309  57]
No circles were found
New frame
[585 311  57]
No circles were found
New frame
[577 319  59]
No circles were found
New frame
[583 321  52]
No circles were found
New frame
[583 317  54]
No circles were found
New frame
[583 317  54]
No circles were found
New frame
[583 319  57]
No circles were found
New frame
[581 323  56]
No circles were found
New frame
[585 327  57]
No circles were found
New frame
[583 329  56]
No circles were found
New frame
[581 331  57]
No circles were found
New frame
[579 333  57]
No circles were found
New frame
[579 333  57]
No circles were found
New frame
[577 337  59]
No circles were found
New frame
[0 0 0]
No circles were found
New frame
[0

New frame
[575 331  59]
No circles were found
New frame
[575 329  59]
No circles were found
New frame
[575 329  59]
No circles were found
New frame
[575 329  59]
No circles were found
New frame
[577 331  59]
No circles were found
New frame
[577 331  59]
No circles were found
New frame
[577 331  59]
No circles were found
New frame
[577 331  59]
No circles were found
New frame
[577 331  57]
No circles were found
New frame
[575 329  57]
No circles were found
New frame
[575 329  59]
No circles were found
New frame
[575 329  59]
No circles were found
New frame
[575 329  59]
No circles were found
New frame
[577 327  59]
No circles were found
New frame
[577 329  59]
No circles were found
New frame
No circles were found
New frame
[577 329  59]
No circles were found
New frame
[577 329  57]
No circles were found
New frame
[577 327  59]
No circles were found
New frame
[577 327  59]
No circles were found
New frame
[575 329  57]
No circles were found
New frame
[573 327  59]
No circles were found
Ne

No circles were found
New frame
[0 0 0]
No circles were found
New frame
[0 0 0]
No circles were found
New frame
[0 0 0]
No circles were found
New frame
[0 0 0]
No circles were found
New frame
[0 0 0]
No circles were found
New frame
[0 0 0]
No circles were found
New frame
[0 0 0]
No circles were found
New frame
[0 0 0]
No circles were found
New frame
[0 0 0]
No circles were found
New frame
[0 0 0]
No circles were found
New frame
[0 0 0]
No circles were found
New frame
[0 0 0]
No circles were found
New frame
[0 0 0]
No circles were found
New frame
No circles were found
New frame
No circles were found
New frame
No circles were found
New frame
No circles were found
New frame
No circles were found
New frame
No circles were found
New frame
No circles were found
New frame
No circles were found
New frame
[0 0 0]
No circles were found
New frame
[0 0 0]
No circles were found
New frame
[0 0 0]
No circles were found
New frame
[0 0 0]
No circles were found
New frame
[0 0 0]
No circles were found
Ne

[343 367  52]
[225 125  54]
[503 103  43]
[163 227  32]
No circles were found
New frame
[487 121  59]
[351 371  50]
[229 109  50]
[339 331  50]
[ 69 357  21]
No circles were found
New frame
[507 115  59]
[341 365  59]
[225 127  57]
[167 227  32]
No circles were found
New frame
[509 119  59]
[353 381  41]
[593 101  37]
[221 121  46]
[353 329  48]
No circles were found
New frame
[509 119  59]
[353 381  41]
[593 101  37]
[221 121  46]
[353 329  48]
No circles were found
New frame
[513 117  59]
[349 367  57]
[227 113  52]
No circles were found
New frame
[507 111  52]
[345 367  52]
[235 115  46]
No circles were found
New frame
[509 113  52]
[351 329  59]
[349 399  57]
[223 117  48]
[593 101  37]
[ 69 357  21]
No circles were found
New frame
[509 111  52]
[349 337  54]
[363 381  41]
[223 115  46]
[345 293  52]
[171 229  30]
No circles were found
New frame
[515 113  54]
[351 401  57]
[349 337  54]
[233 119  50]
No circles were found
New frame
[515 113  54]
[367 381  41]
[239 115  46]
[593 101